// Re-export types and functions generated by the Compact compiler
// Adjust the path './generated/registry' if the compiler output differs.

export * from './generated/registry';

// You can also add custom helper functions or constants related to the contract here if needed.

// export * from './generated/registry'; // Example export 